
MERGE 

LINKS
```{r}
LGscorriente="https://github.com/jimenafelipe/TRABAJO1/raw/master/Gscorriente.csv"

LGHealthExp="https://github.com/jimenafelipe/TRABAJO1/raw/master/GovernmentHealthExp.csv"

LGPBI="https://github.com/jimenafelipe/TRABAJO1/raw/master/GPBI.csv"

LGbolsillo="https://github.com/jimenafelipe/TRABAJO1/raw/master/Gbolsillo.csv"

Lcobertura="https://github.com/jimenafelipe/TRABAJO1/raw/master/cobertura.csv"
```

Cargas
```{r}
Gscorriente=read.csv(LGscorriente,stringsAsFactors = F)
GHealthExp=read.csv(LGHealthExp,stringsAsFactors = F)
GPBI=read.csv(LGPBI,stringsAsFactors = F)
Gbolsillo=read.csv(LGbolsillo,stringsAsFactors = F)
cobertura=read.csv(Lcobertura,stringsAsFactors = F)
```

```{r}
names(Gbolsillo)
names(cobertura)
names(GPBI)
names(Gscorriente)
names(GHealthExp)
```



Merge
```{r}
totalData=merge(Gscorriente,GPBI,all.x = T, all.y = T)
totalData=merge(totalData,Gbolsillo,all.x = T, all.y = T)
#totalData[!complete.cases(totalData),]
totalData=merge(totalData,cobertura,all.x = T, all.y = T)
totalData=merge(totalData,GHealthExp,all.x = T, all.y = T)

```

```{r}
totalData=na.omit(totalData)
```

